### ISSUE TITLE
Terraform: unexpected Content-Type

### ISSUE THREAD

**Issue by python2015ajax** [DataDog/stratus-red-team#118]
problem starting stratus-red-team

2022/05/23 00:39:19 Checking your authentication against AWS
2022/05/23 00:39:20 Installing Terraform in /root/.stratus-red-team/terraform
2022/05/23 00:39:20 error installing Terraform: unexpected Content-Type: "application/vnd+hashicorp.releases-api.v0+json"

**Comment by christophetd** [comment]
Hello!

Thanks for reporting, I confirm I'm experiencing the same issue on a fresh install. I'm investigating.

**Comment by christophetd** [comment]
Seeing similar reports in https://discuss.hashicorp.com/t/cannot-run-terraform-provider-tests-unexpected-content-type-application-vnd-hashicorp-releases-api-v0-json/39643

Appears to be caused by https://github.com/hashicorp/hc-install/issues/56, fixed in v0.3.2. See #119 for upcoming fix in Stratus Red Team (will be released as part of v1.7.1

**Comment by python2015ajax** [comment]
Thanks brother!!!
