### ISSUE TITLE
Support detonating attack techniques against existing infrastructure

### ISSUE THREAD

**Issue by christophetd** [DataDog/stratus-red-team#63]
Vote to show interest, and comment with why you'd need to use your own existing infrastructure!

**Comment by christophetd** [comment]
@akingscote @MikeCain21  @wushingmushine thanks for upvoting this issue, can you give more detail as to why you'd be using this?

**Comment by Yashvendra** [comment]
Hey @christophetd, rather than attacking/exploiting an existing infra, can't we just simulate an attack and show if their current environment is vulnerable to corresponding technique or not.

**Comment by MIkeCain21** [comment]
Hey @christophetd , Currently we have some automation in place which takes care of the warmup, revert, and cleanup phases of some short-lived infrastructure used for training. I would love to throw this tool into the mix so that we could simulate the current attack techniques and validate that our users have the knowledge to detect them / find the detections in other tools.

**Comment by christophetd** [comment]
Thanks for the feedback! The current complexity is about validating prerequisite infrastructure, and making sure it's left in a clean state.
